services:
  - type: web
    name: notreprague
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    plan: free
    branch: main
    autoDeploy: true
